[project]
name = "falling-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "haruki26", email = "h826.a519@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "openvino>=2025.0,<2027",
    "numpy>=1.26,<3",
    "opencv-python>=4.8,<5",
]

[project.scripts]
falling-prediction = "falling_prediction:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
